name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chatpdf:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chatpdf:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chatpdf:buildcache,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove existing containers
        run: |
          sudo docker stop chatpdf || true
          sudo docker rm chatpdf || true

      - name: Remove unused images
        run: sudo docker system prune -af

      - name: Pull new image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/chatpdf:latest

      - name: Run Docker container
        run: |
          sudo docker run -d \
            --name chatpdf \
            --restart unless-stopped \
            -p 8080:8080 \
            ${{ secrets.DOCKER_USERNAME }}/chatpdf:latest

      - name: Verify deployment
        run: |
          echo "Waiting for container to start..."
          sleep 10
          if ! sudo docker ps | grep -q chatpdf; then
            echo "Container failed to start"
            sudo docker logs chatpdf
            exit 1
          fi
