name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Clean up Docker resources
        run: |
          docker system prune -af
          docker volume prune -f

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t vigneshragu10/chatpdf:latest .

      - name: Publish image to docker hub
        run: docker push vigneshragu10/chatpdf:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove all existing containers
        run: |
          sudo docker stop $(sudo docker ps -aq) || true
          sudo docker rm -f $(sudo docker ps -aq) || true

      - name: Remove cache memory
        run: sudo docker system prune -a -f

      - name: Pull image from Docker Hub
        run: sudo docker pull vigneshragu10/chatpdf:latest

      - name: Delete Old Container
        run: sudo docker rm -f chatpdf || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name chatpdf vigneshragu10/chatpdf:latest
